pipeline {
  agent none

  environment {
    AWS_REGION = 'us-east-1'
    ECR_REPO   = '992382545251.dkr.ecr.us-east-1.amazonaws.com/rotemamit/final_cicd_exam'
    APP_DIR    = 'calculator-app-v2'
    PROD_IP    = '54.91.175.237'
  }

  stages {
    stage('Build Image') {
      agent any
      steps {
        dir("${APP_DIR}") {
          sh 'docker build -t calculator-app:${BUILD_NUMBER} .'
        }
      }
    }

    stage('Test') {
      agent {
        docker {
          image 'python:3.11-slim'
          args '-u root'
        }
      }
      steps {
        dir("${APP_DIR}") {
          sh '''
            pip install --no-cache-dir -r requirements.txt pytest
            PYTHONPATH=. pytest --junitxml=results.xml tests/
          '''
        }
      }
      post {
        always {
          junit "${APP_DIR}/results.xml"
        }
      }
    }

    stage('Push to ECR - PR') {
      agent any
      when { changeRequest() }
      steps {
        withAWS(credentials: '47554446-a967-4a09-b5b0-33ca9dd7c93f', region: "${AWS_REGION}") {
          sh '''
            aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REPO}
            docker tag calculator-app:${BUILD_NUMBER} ${ECR_REPO}:pr-${CHANGE_ID}-${BUILD_NUMBER}
            docker push ${ECR_REPO}:pr-${CHANGE_ID}-${BUILD_NUMBER}
          '''
        }
      }
    }

    stage('Push to ECR - Master') {
      agent any
      when { branch 'main' }
      steps {
        withAWS(credentials: '47554446-a967-4a09-b5b0-33ca9dd7c93f', region: "${AWS_REGION}") {
          sh '''
            aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REPO}
            docker tag calculator-app:${BUILD_NUMBER} ${ECR_REPO}:build-${BUILD_NUMBER}
            docker tag calculator-app:${BUILD_NUMBER} ${ECR_REPO}:latest
            docker push ${ECR_REPO}:build-${BUILD_NUMBER}
            docker push ${ECR_REPO}:latest
          '''
        }
      }
    }

	stage('Deploy to Production') {
  agent any
  when { branch 'main' }
  steps {
    withAWS(credentials: '47554446-a967-4a09-b5b0-33ca9dd7c93f', region: "${AWS_REGION}") {
      sshagent(credentials: ['SSH Key']) {
        script {
          def ecrLogin = sh(script: "aws ecr get-login-password --region ${AWS_REGION}", returnStdout: true).trim()
          sh """
            ssh -o StrictHostKeyChecking=no ubuntu@${PROD_IP} '
              echo ${ecrLogin} | docker login --username AWS --password-stdin ${ECR_REPO}
              docker pull ${ECR_REPO}:latest
              docker stop calculator-app || true
              docker rm calculator-app || true
              docker run -d --name calculator-app -p 5000:5000 ${ECR_REPO}:latest
            '
          """
        }
      }
    }
  }
}
